export const COLORS = {
    primary: "#2F80ED",
    background: "#FFFFFF",
    text: "#333333",
    border: "#E0E0E0",
    error: "#EB5757",
    success: "#27AE60",
    textDark:'#1A1D1F',
    textSecondary:'#6E7275',
    textLight:'#9EA4AB',
    textOrange:'#FF7E54',
    colorCerulean: "#1a759f",
    colorWhite: "#fff",
    colorBlack: "#000",
    colorGrey: "grey",
    colorRed: "red",
    colorLightGrey: "#eee",
    colorGreen:"#29b365",
    colorOrage:"#FA4A0C",
    colorAppleGreen: "#a0d36c",
    colorLimeGreen: "#d0e57e",
    colorOrageLight:"#FA4A0C",

  };
